### ISSUE TITLE
How to set correct login URL for frontend?

### ISSUE THREAD

**Issue by matt-cbell** [SciCatProject/frontend#1025]
### Summary

When running the frontend code against a backend-next instance, without any LDAP integration, and only using the functional accounts, it authenticates to "http://127.0.0.1:3000/auth/msad".

Authenticating to the backend-next instance via Swagger on "http://localhost:3000/api/v3/auth/login" works fine.  How do I configure the frontend instance to use this URL for login instead?

### Steps to Reproduce

Run scicat mongodb, backend-next and frontend instances locally with no LDAP integration for backend-next.  Attempt to login using the front end and any functional account.  

### Current Behaviour

The login appears to work, but it's not possible to navigate beyond that first login page.  Also note that the frontend attempts to hit the URL "http://127.0.0.1:3000/auth/msad", which returns a HTTP 404.

### Expected Behaviour

The correct URL should be hit by the frontend so that a valid user token is returned.

**Comment by linupi** [comment]
Did you add/change the `accessTokenPrefix` in the fronted configuration? Compared to the _old_ backend there is a little difference here. To make the login work the `accessTokenPrefix`  has to be set to `"Bearer "` instead of just an empty string for the old backend.

Have a look at the scicat-live configuration for the new backend, maybe that helps: https://github.com/SciCatProject/scicatlive/blob/18a5b4d0d1b1f389dabb86cf4b43b4a02257f2c5/config/frontend/config.json#L2

**Comment by matt-cbell** [comment]
Yes, that worked, thank you!  I'll close the issue.
