### ISSUE TITLE
Dockerfile delayed build issues

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/frontend#825]
In #774, the Dockerfile was modified to allow passing an angular environment through an environment variable. This makes deployments easier as sites don't have to maintain their own docker build processes for each version of container they have (dev, stage, prod.) It does this by delaying the angular build to container startup rather than image build.

However, thss presents a couple of issues for orchestration.

We are using Rancher which sits on top of Kubernetes (I admit that here that I am no expert with k8s). When I redeploy a workload, I would like for the current running workload to stay running until the new workload has started. If the new workload fails to start for some reason, I would like to stay with the original workload and not switch to the failing one.

The issue with this new Dockerfile is that k8s is detecting that the workload has successfully started as soon as nginx has started up, and switches over to the new workload. But catanie is not yet available, as the npx build has not yet started. This can take up to three minutes to complete, meaning three minutes of downtime. Worse, if the npx  build fails (for example, something went over budget), then k8s is perfectly happy as its signal for success was that nginx has started up, and not that the angular build has succeeded.

Is there a way to change orchestrator's detection of success to be based on the angular build rather than the nginx startup, perhaps through the use of signals?

**Comment by stephan271** [comment]
I would rather have a solution, where the container is immediately ready to be used, without going through a lengthy build process. Cant we have a single docker file but with prebuilt angular build, reading the env dependent configurations at run time ? @minottic could you have a look ?

**Comment by minottic** [comment]
@dylanmcreynolds , sorry for the late reply I was on holiday and, yes, you are right the build is very slow.

I think there are two aspects to it, what docker does and how you deploy. Here, the run of docker is very slow (and this time was before used in the build), and googling, there are some ways to optimes it, for example by increasing the memory or disabling the source-map option, both, by a certain extent, on the docker side. 

For what concerns the deployment with a long startup time on k8s (what you point out here I think: _for example, something went over budget_), the solution is usually to increase the initialDelaySeconds in the [startup probe or liveness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes). 

To avoid downtime, when deploying on k8s, some solutions allow you to wait for the pod to be healthy before switching off the old one (I know it exists for helm). Are you using kubectl or helm or anything else? Also, maybe setting the initialDelaySeconds in the readiness probe already solves the downtime issue (I will check).

I am happy to have a chat if that helps

**Comment by stephan271** [comment]
Cant we move the build process at build time, rather than run time ?

**Comment by minottic** [comment]
from what I understood, the build needs to have the `environment.*.ts` file to work, so if we pass it in the build every configuration will need its docker image. The build process at run time, conversely, was thought to be able to have one single image, independent from the specific configuration, and enabling the option of mounting configuration files just before run time (for example, with the catanie image it is now possible to run: `docker run catanie -v environment.dev.ts:environment.dev.ts` or `docker run catanie -v environment.prod.ts:environment.prod.ts`). 
Not too sure if this answers your question.

**Comment by stephan271** [comment]
Yes, it does, thx !

**Comment by dylanmcreynolds** [comment]
I'm actually using Rancher's implementation on top of k8s. I'll play with startup checks and health check, thanks for the suggestion.

This is an interesting question. I love the feature you added because I don't have to create my own unique docker image. But if I had a choice of having a delay during build time vs. deploy time for a production image, I would definitely choose build time.

**Comment by ibressler** [comment]
Hi, while I'd love environment agnostic builds as well, I just want to add another aspect: At the moment I have the catanie image running on a bare k8s node (VM) limited to 2G RAM. Which works fine as long as the image is built on another machine because this needs much more resources with angular (as mentioned above) than running it.
Therefore, building stuff when starting the container would kind of break this setup. (Tested earlier that building catanie on that node does not work ;)

**Comment by minottic** [comment]
hi @ibressler , yes, as mentioned with Dylan, I agree the time+resource requirement is high, and doing it during the run can be a problem for some environments. But even in this case, I would be inclined to keep this dockerfile as I think it cannot be env specific basically because it is not scalable (as an end point I imagine facilities being able to install scicat without even having access to the code base -github-, just by pulling an image and mounting the configuration, plus I am not a fan of having 100 config files in github). So, in summary, I think the dockerfile/image needs to be config agnostic.

To address the resource consumption I see these possibilities (sorted following my preference :)):

1. we understand if config variables can be provided after the angular build or if there is a way to speed up the angular build
2. we could provide this dockerfile as a base image, that you later run somewhere else (not on k8s, e.g. on the CI runner) with more resources, mounting the config files and then pushing to your registry, which you later pull from docker
3. we move the config files somewhere else (as Fredrik was suggesting, e.g. to catamel)

I don't fancy too much 3, as it creates a server-> client relation, instead of the usual client->server one.

**Comment by dylanmcreynolds** [comment]
Personally, I strongly favor option 3 that @bolmsten proposed. I can imagine adding "configuration management" to the services that catamel provides, a service that provides such for multiple areas including catamel, zip-service and others. Having one place for configurations that affect the suite of services that are SciCat would make deployment (and learning how to do it) easier.

**Comment by ibressler** [comment]
> Having one place for configurations that affect the suite of services that are SciCat would make deployment (and learning how to do it) easier.

I support that idea, especially since properly enabling/disabling some features require changes in both parts config (catanie & catamel, at least) to be effective.

**Comment by stephan271** [comment]
Would https://nx.app/angular-cli-faster  be of any help here ? Can we make use of such caching functionality ?

Concerning option 3: I guess this is only an option if we migrate configuration settings to a new conf file ouside the current environment files. We would also loose any build time code optimization in this case, I assume.

**Comment by dylanmcreynolds** [comment]
@stephan271...that seems like something nice for development, but I would be nervous make an external service like this a dependency for starting up the container.

**Comment by stephan271** [comment]
I am not sure, that the external service is actually needed, by default it is a local caching as far as I understood...I may be wrong however

**Comment by nitrosx** [comment]
This issue should have been solved with PR #915.
Closing it. I will re-open if needed
