### ISSUE TITLE
Question: navigate from Raw Dataset to its Derived Datasets

### ISSUE THREAD

**Issue by dylanmcreynolds** [SciCatProject/frontend#932]
The frontend has a very convenient method for navigating from a derived dataset to one or more of its related raw datasets, by providing urls in the "Input Datasets" field.

But is there a similar mechanism to go the other direction? If I'm looking at a Raw Dataset I'd like to easily see the various related Derived Datasets. Is there any mechanism that I'm not seeing for this?

**Comment by henrikjohansson712** [comment]
This is actually kind of implemented but it's connected to the reduce/analyze workflow. In the "Reduce" tab of the dataset details view there's a table of datasets derived from that particular dataset. The problem is that the reduce workflow isn't finished and the development of it has kind of stalled. I propose we move the existing table out of the reduce workflow into it's own entity as this is a useful feature to have.

**Comment by nitrosx** [comment]
The community support @henrikjohansson712 proposal during SciCat meeting on 2022/03/23. 

> move the existing table out of the reduce workflow into it's own entity as this is a useful feature to have.
